language: python
python:
  - "3.7"
  - "3.8"
env:
  - TENSORFLOW_VERSION=1.15 MODULE=estimator
  - TENSORFLOW_VERSION=2.0 MODULE=estimator
  - TENSORFLOW_VERSION=2.1 MODULE=estimator
  - TENSORFLOW_VERSION=2.2 MODULE=estimator
  - TENSORFLOW_VERSION=2.3 MODULE=estimator
  - TENSORFLOW_VERSION=2.4 MODULE=estimator
  - TENSORFLOW_VERSION=2.5 MODULE=estimator
  - TENSORFLOW_VERSION=2.6 MODULE=estimator
  - TENSORFLOW_VERSION=1.15 MODULE=keras
  - TENSORFLOW_VERSION=2.0 MODULE=keras
  - TENSORFLOW_VERSION=2.1 MODULE=keras
  - TENSORFLOW_VERSION=2.2 MODULE=keras
  - TENSORFLOW_VERSION=2.3 MODULE=keras
  - TENSORFLOW_VERSION=2.4 MODULE=keras
  - TENSORFLOW_VERSION=2.5 MODULE=keras
  - TENSORFLOW_VERSION=2.6 MODULE=keras
matrix:
  allow_failures:
    - env: TENSORFLOW_VERSION=2.1 MODULE=keras
    - env: TENSORFLOW_VERSION=1.15 MODULE=keras
    - env: TENSORFLOW_VERSION=2.0 MODULE=keras
    - env: TENSORFLOW_VERSION=2.1 MODULE=keras
    - env: TENSORFLOW_VERSION=2.2 MODULE=keras
  exclude:
    - python: 3.8
      env: TENSORFLOW_VERSION=1.15 MODULE=estimator
    - python: 3.8
      env: TENSORFLOW_VERSION=2.0 MODULE=estimator
    - python: 3.8
      env: TENSORFLOW_VERSION=2.1 MODULE=estimator
    - python: 3.8
      env: TENSORFLOW_VERSION=1.15 MODULE=keras
    - python: 3.8
      env: TENSORFLOW_VERSION=2.0 MODULE=keras
    - python: 3.8
      env: TENSORFLOW_VERSION=2.1 MODULE=keras

sudo: false

before_install:
  - pip install pytest-cov==2.4.0
  - pip install tensorflow==$TENSORFLOW_VERSION
  - pip install codecov
  - export PYTHONPATH=$PYTHONPATH:$pwd

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=deep_recommenders tests/$MODULE

notifications:
  email: wangyao.sr@gmail.com

after_success:
  - codecov


