name: CI
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: [3.7, 3.8]
        tensorflow: ["1.15", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5"]
        module: [estimator, keras]
        exclude:
          - python: 3.8
            tensorflow: "1.15"
          - python: 3.8
            tensorflow: "2.0"
          - python: 3.8
            tensorflow: "2.1"
          - module: keras
            tensorflow: "1.15"
          - module: keras
            tensorflow: "2.0"
          - module: keras
            tensorflow: "2.1"
          - module: keras
            tensorflow: "2.2"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow==${{ matrix.tensorflow }}
          pip install -r requirements.txt
      - name: Set python path environment variables
        run: export PYTHONPATH=$PYTHONPATH:/
      - name: Test with pytest
        run: |
          pip install pytest-cov
          pytest --cov=deep_recommenders/${{ matrix.module }} tests/${{ matrix.module }}
        env:
          PYTHONPATH: .
      - name: Coverage with codecov
        run: |
          pip install codecov
          codecov
